version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_eventos
    environment:
      MYSQL_ROOT_PASSWORD: Anderson#1
      MYSQL_DATABASE: eventos
    ports:
      - "3306:3306"
	  